### ISSUE TITLE
about

### ISSUE THREAD

**Issue by StarSuomaLi** [StarSuomaLi/comments#5]
https://starsuomali.github.io/about/

**Comment by Charon115** [comment]
![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)![:025:](https://starsuomali.github.io/imgs/smilies/25.png)
